name: Azure Key Vault Integration

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  retrieve-secrets:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      database-url: ${{ steps.keyvault.outputs.database-url }}
      api-key: ${{ steps.keyvault.outputs.api-key }}
      storage-connection: ${{ steps.keyvault.outputs.storage-connection }}
    
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Get secrets from Key Vault
      id: keyvault
      uses: Azure/get-keyvault-secrets@v1
      with:
        keyvault: "cyberdine-keyvault"
        secrets: 'database-url, api-key, storage-connection'